version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ember-template-lint
    versions:
    - 2.19.0
    - 2.20.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: leaflet
    versions:
    - 1.7.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-cli-mirage
    versions:
    - 2.0.1
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: ember-concurrency
    versions:
    - 2.0.1
    - 2.0.2
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
  - dependency-name: grunt-contrib-jshint
    versions:
    - 3.0.0
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
  - dependency-name: grunt-contrib-nodeunit
    versions:
    - 2.1.0
  - dependency-name: grunt-cli
    versions:
    - 1.3.2
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 3.0.0
  - dependency-name: bower
    versions:
    - 1.8.4
  - dependency-name: grunt-wiredep
    versions:
    - 3.0.1
  - dependency-name: grunt-bower
    versions:
    - 0.21.4
