---
language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install -g yarn
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install

scripts:
  test: ''
