---
language: node_js
node_js:
  - "12"

dist: trusty

addons:
  chrome: stable

before_install:
  - mv .ember-cli.dst .ember.cli
  - mv config/environment.js.dst /config/environment.js

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - npm test
