version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1
jobs:
  build:
    docker:
      - image: cimg/node:12.18-browsers
        environment:
          JOBS: 2
          DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    working_directory: ~/atlmaps
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: NPM Install
          command: npm install --non-interactive
      - run: echo 'export PATH=~/atlmaps/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: npm test
      # - deploy:
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         ember deploy production
      #       fi